### ISSUE TITLE
Fedora 34 build can't make, do you know what could be the error ?

### ISSUE THREAD

**Issue by richieloro** [vapoursynth/vapoursynth#688]
Hello I followed this tutorial perfectly : https://www.l33tmeatwad.com/vapoursynth101/software-setup
I still can't install vapoursynth, do you know what is the error related to ?
I satisfy all the dependencies.
Thank you so much.

`$ make`
```
  CXX      src/core/libvapoursynth_la-genericfilters.lo
src/core/genericfilters.cpp: In function ‘void genericCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)’:
src/core/genericfilters.cpp:443:31: error: ‘numeric_limits’ is not a member of ‘std’
  443 |                 d->thf = std::numeric_limits<float>::max();
      |                               ^~~~~~~~~~~~~~
src/core/genericfilters.cpp:443:46: error: expected primary-expression before ‘float’
  443 |                 d->thf = std::numeric_limits<float>::max();
      |                                              ^~~~~
src/core/genericfilters.cpp:529:46: error: ‘numeric_limits’ is not a member of ‘std’
  529 |             if (std::abs(matrix_sumf) < std::numeric_limits<float>::epsilon())
      |                                              ^~~~~~~~~~~~~~
src/core/genericfilters.cpp:529:61: error: expected primary-expression before ‘float’
  529 |             if (std::abs(matrix_sumf) < std::numeric_limits<float>::epsilon())
      |                                                             ^~~~~
src/core/genericfilters.cpp:529:61: error: expected ‘)’ before ‘float’
  529 |             if (std::abs(matrix_sumf) < std::numeric_limits<float>::epsilon())
      |                ~                                            ^~~~~
      |                                                             )
src/core/genericfilters.cpp: In function ‘const VSFrameRef* levelsGetframeF(int, int, void**, void**, VSFrameContext*, VSCore*, const VSAPI*)’:
src/core/genericfilters.cpp:852:69: error: ‘numeric_limits’ is not a member of ‘std’
  852 |                 if (std::abs(d->gamma - static_cast<T>(1.0)) < std::numeric_limits<T>::epsilon()) {
      |                                                                     ^~~~~~~~~~~~~~
src/core/genericfilters.cpp:852:85: error: expected primary-expression before ‘>’ token
  852 |                 if (std::abs(d->gamma - static_cast<T>(1.0)) < std::numeric_limits<T>::epsilon()) {
      |                                                                                     ^
src/core/genericfilters.cpp:852:88: error: ‘::epsilon’ has not been declared
  852 |                 if (std::abs(d->gamma - static_cast<T>(1.0)) < std::numeric_limits<T>::epsilon()) {
      |                                                                                        ^~~~~~~
make: *** [Makefile:1714: src/core/libvapoursynth_la-genericfilters.lo] Error 1
```

**Comment by sekrit-twc** [comment]
Are you building from master? This was fixed recently.

**Comment by richieloro** [comment]
I did 
```
git clone https://github.com/vapoursynth/vapoursynth.git
cd /vapoursynth
./autogen.sh
./configure  --prefix=/usr
make
make install 
```

**Comment by richieloro** [comment]
FRESH FEDORA 34 VIRTUALBOX

```shell
[testr@fedora vapoursynth]$ ./configure  --prefix=/usr
configure: loading site script /usr/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking whether gcc is Clang... no
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZIMG... yes
checking for library containing dlopen... -ldl
checking for sched_getaffinity... yes
checking for cpuset_getaffinity... no
checking for a Python interpreter with version >= 3... python
checking for python... /usr/bin/python
checking for python version... 3.9
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.9/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python3.9/site-packages
checking for PYTHON3... yes
checking for cython3... no
checking for cython... cython
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking for library containing libiconv_open... no
checking for library containing iconv_open... none required
checking for LIBASS... yes
checking for FFMPEG... yes
checking for IMAGEMAGICK... yes
checking whether imagemagick is usable... yes
checking for TESSERACT... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating pc/vapoursynth.pc
config.status: creating pc/vapoursynth-script.pc
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
```
Use ctrl+f `error`
```shell
[testr@fedora vapoursynth]$ make -j4
  CYTHON   src/cython/vapoursynth.c
  CXX      src/vspipe/vspipe.o
  CXX      src/vsscript/libvapoursynth_script_la-vsscript.lo
  CXX      src/core/libvapoursynth_la-boxblurfilter.lo
/usr/lib64/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/testr/.installs/vapoursynth/src/cython/vapoursynth.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
  CXX      src/core/libvapoursynth_la-cachefilter.lo
  CXX      src/core/libvapoursynth_la-cpufeatures.lo
  CXX      src/core/libvapoursynth_la-genericfilters.lo
  CXX      src/core/kernel/libvapoursynth_la-cpulevel.lo
  CXX      src/core/kernel/libvapoursynth_la-generic.lo
  CC       src/core/kernel/libvapoursynth_la-merge.lo
  CC       src/core/kernel/libvapoursynth_la-planestats.lo
src/core/kernel/merge.c: In function ‘vs_mask_merge_premul_word_c’:
src/core/kernel/merge.c:178: warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
  178 | #pragma warning(push)
      | 
src/core/kernel/merge.c:179: warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
  179 | #pragma warning(disable:4146)
      | 
src/core/kernel/merge.c:185: warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
  185 | #pragma warning(pop)
      | 
  CC       src/core/kernel/libvapoursynth_la-transpose.lo
  CXX      src/core/libvapoursynth_la-lutfilters.lo
  CC       src/core/libvapoursynth_la-mergefilters.lo
  CC       src/core/libvapoursynth_la-reorderfilters.lo
  CXX      src/core/libvapoursynth_la-settings.lo
  CC       src/core/libvapoursynth_la-simplefilters.lo
  CXX      src/core/libvapoursynth_la-textfilter.lo
  CXX      src/core/libvapoursynth_la-vsapi.lo
  CXX      src/core/libvapoursynth_la-vscore.lo
  CXX      src/core/libvapoursynth_la-vslog.lo
  CXX      src/core/libvapoursynth_la-vsresize.lo
  CXX      src/core/libvapoursynth_la-vsthreadpool.lo
  CXX      src/core/kernel/x86/libvapoursynth_la-generic_sse2.lo
  CC       src/core/kernel/x86/libvapoursynth_la-merge_sse2.lo
  CC       src/core/kernel/x86/libvapoursynth_la-planestats_sse2.lo
  CC       src/core/kernel/x86/libvapoursynth_la-transpose_sse2.lo
  CXX      src/core/libexprfilter_la-exprfilter.lo
  CXX      src/core/kernel/x86/libvapoursynth_avx2_la-generic_avx2.lo
  CC       src/core/kernel/x86/libvapoursynth_avx2_la-merge_avx2.lo
  CC       src/core/kernel/x86/libvapoursynth_avx2_la-planestats_avx2.lo
  CC       src/filters/subtext/libsubtext_la-text.lo
  CC       src/filters/subtext/libsubtext_la-common.lo
src/core/exprfilter.cpp:1642:50: error: ‘numeric_limits’ is not a member of ‘std’
 1642 |     static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                  ^~~~~~~~~~~~~~
src/core/exprfilter.cpp:1642:66: error: expected primary-expression before ‘>’ token
 1642 |     static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                                  ^
src/core/exprfilter.cpp:1642:69: error: ‘::digits’ has not been declared
 1642 |     static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                                     ^~~~~~
src/core/exprfilter.cpp: In static member function ‘static T {anonymous}::ExprInterpreter::clamp_int(float, int)’:
src/core/exprfilter.cpp:1645:87: error: ‘numeric_limits’ is not a member of ‘std’
 1645 |         return static_cast<T>(std::lrint(std::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                                                       ^~~~~~~~~~~~~~
src/core/exprfilter.cpp:1645:103: error: expected primary-expression before ‘>’ token
 1645 |         return static_cast<T>(std::lrint(std::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                                                                       ^
src/core/exprfilter.cpp:1645:106: error: ‘::min’ has not been declared; did you mean ‘std::min’?
 1645 |         return static_cast<T>(std::lrint(std::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                                                                          ^~~
      |                                                                                                          std::min
In file included from /usr/include/c++/11/algorithm:62,
                 from src/core/exprfilter.cpp:21:
/usr/include/c++/11/bits/stl_algo.h:3455:5: note: ‘std::min’ declared here
 3455 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
  CXX      src/filters/subtext/libsubtext_la-image.lo
  CXX      src/filters/subtext/libsubtext_la-toass.lo
src/filters/subtext/image.cpp: In function ‘void imageFileCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)’:
src/filters/subtext/image.cpp:361:21: warning: ‘void av_register_all()’ is deprecated [-Wdeprecated-declarations]
  361 |     av_register_all();
      |                     ^
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:1955:6: note: declared here
 1955 | void av_register_all(void);
      |      ^~~~~~~~~~~~~~~
src/filters/subtext/image.cpp:362:26: warning: ‘void avcodec_register_all()’ is deprecated [-Wdeprecated-declarations]
  362 |     avcodec_register_all();
      |                          ^
In file included from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavcodec/avcodec.h:2767:6: note: declared here
 2767 | void avcodec_register_all(void);
      |      ^~~~~~~~~~~~~~~~~~~~
src/filters/subtext/image.cpp:430:66: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  430 |        if (!isSupportedCodecID(fctx->streams[stream_index]->codec->codec_id))
      |                                                             ^~~~~

In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:430:66: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  430 |        if (!isSupportedCodecID(fctx->streams[stream_index]->codec->codec_id))
      |                                                             ^~~~~

In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:430:66: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  430 |        if (!isSupportedCodecID(fctx->streams[stream_index]->codec->codec_id))
      |                                                             ^~~~~

In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:434:58: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  434 |                 if (isSupportedCodecID(fctx->streams[i]->codec->codec_id)) {
      |                                                          ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:434:58: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  434 |                 if (isSupportedCodecID(fctx->streams[i]->codec->codec_id)) {
      |                                                          ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:434:58: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  434 |                 if (isSupportedCodecID(fctx->streams[i]->codec->codec_id)) {
      |                                                          ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:448:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  448 |         AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:448:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  448 |         AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:448:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  448 |         AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:458:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  458 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:458:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  458 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:458:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  458 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:462:69: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  462 |     memcpy(d.avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                             ^~~~~

In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:462:69: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  462 |     memcpy(d.avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                             ^~~~~

In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:462:69: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  462 |     memcpy(d.avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                             ^~~~~

In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:482:56: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  482 |     av_opt_get_image_size(fctx->streams[stream_index]->codec, "video_size", 0, &d.vi.width, &d.vi.height);
      |                                                        ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:482:56: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  482 |     av_opt_get_image_size(fctx->streams[stream_index]->codec, "video_size", 0, &d.vi.width, &d.vi.height);
      |                                                        ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:482:56: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  482 |     av_opt_get_image_size(fctx->streams[stream_index]->codec, "video_size", 0, &d.vi.width, &d.vi.height);
      |                                                        ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:487:27: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  487 |     av_init_packet(&packet);
      |                           ^
In file included from /usr/include/ffmpeg/libavcodec/bsf.h:30,
                 from /usr/include/ffmpeg/libavcodec/avcodec.h:44,
                 from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
src/filters/subtext/image.cpp:514:50: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  514 |                 if (fctx->streams[stream_index]->codec->codec_id == AV_CODEC_ID_DVD_SUBTITLE) {
      |                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:514:50: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  514 |                 if (fctx->streams[stream_index]->codec->codec_id == AV_CODEC_ID_DVD_SUBTITLE) {
      |                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:514:50: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  514 |                 if (fctx->streams[stream_index]->codec->codec_id == AV_CODEC_ID_DVD_SUBTITLE) {
      |                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:653:52: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  653 |             AVCodecID codec_id = fctx->streams[i]->codec->codec_id;
      |                                                    ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:653:52: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  653 |             AVCodecID codec_id = fctx->streams[i]->codec->codec_id;
      |                                                    ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:653:52: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  653 |             AVCodecID codec_id = fctx->streams[i]->codec->codec_id;
      |                                                    ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:671:53: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  671 |             av_opt_get_image_size(fctx->streams[i]->codec, "video_size", 0, &width, &height);
      |                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:671:53: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  671 |             av_opt_get_image_size(fctx->streams[i]->codec, "video_size", 0, &width, &height);
      |                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:671:53: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  671 |             av_opt_get_image_size(fctx->streams[i]->codec, "video_size", 0, &width, &height);
      |                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp: In function ‘ASS_Track* convertToASS(const char*, const char*, size_t, ASS_Library*, const char*, const char*, char*, size_t)’:
src/filters/subtext/toass.cpp:64:21: warning: ‘void av_register_all()’ is deprecated [-Wdeprecated-declarations]
   64 |     av_register_all();
      |                     ^
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:1955:6: note: declared here
 1955 | void av_register_all(void);
      |      ^~~~~~~~~~~~~~~
src/filters/subtext/toass.cpp:65:26: warning: ‘void avcodec_register_all()’ is deprecated [-Wdeprecated-declarations]
   65 |     avcodec_register_all();
      |                          ^
In file included from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavcodec/avcodec.h:2767:6: note: declared here
 2767 | void avcodec_register_all(void);
      |      ^~~~~~~~~~~~~~~~~~~~
src/filters/subtext/toass.cpp:130:60: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  130 |     enum AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                            ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:130:60: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  130 |     enum AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                            ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:130:60: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  130 |     enum AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                            ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:149:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  149 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:149:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  149 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:149:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  149 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:156:67: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  156 |             memcpy(avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                                   ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:156:67: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  156 |             memcpy(avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                                   ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:156:67: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  156 |             memcpy(avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                                   ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:220:27: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  220 |     av_init_packet(&packet);
      |                           ^
In file included from /usr/include/ffmpeg/libavcodec/bsf.h:30,
                 from /usr/include/ffmpeg/libavcodec/avcodec.h:44,
                 from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
  CC       src/filters/subtext/libsubtext_la-toutf8.lo
  CC       src/filters/eedi3/libeedi3_la-eedi3.lo
make: *** [Makefile:1625: src/core/libexprfilter_la-exprfilter.lo] Error 1
make: *** Waiting for unfinished jobs....
[testr@fedora vapoursynth]$ make install
  CXXLD    libvapoursynth-script.la
  CXXLD    vspipe
  CXX      src/core/libexprfilter_la-exprfilter.lo
src/core/exprfilter.cpp:1642:50: error: ‘numeric_limits’ is not a member of ‘std’
 1642 |     static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                  ^~~~~~~~~~~~~~
src/core/exprfilter.cpp:1642:66: error: expected primary-expression before ‘>’ token
 1642 | static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                              ^

src/core/exprfilter.cpp:1642:69: error: ‘::digits’ has not been declared
 1642 | static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                                 ^~~~~~

src/core/exprfilter.cpp: In static member function ‘static T {anonymous}::ExprInterpreter::clamp_int(float, int)’:
src/core/exprfilter.cpp:1645:87: error: ‘numeric_limits’ is not a member of ‘std’
 1645 | <T>(std::lrint(std::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                             ^~~~~~~~~~~~~~

src/core/exprfilter.cpp:1645:103: error: expected primary-expression before ‘>’ token
 1645 | td::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                             ^

src/core/exprfilter.cpp:1645:106: error: ‘::min’ has not been declared; did you mean ‘std::min’?
 1645 | :min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                             ^~~
      |                                                             std::min
In file included from /usr/include/c++/11/algorithm:62,
                 from src/core/exprfilter.cpp:21:
/usr/include/c++/11/bits/stl_algo.h:3455:5: note: ‘std::min’ declared here
 3455 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make: *** [Makefile:1625: src/core/libexprfilter_la-exprfilter.lo] Error 1
```

```shell
[testr@fedora vapoursynth]$ sudo make install
  CXX      src/core/libexprfilter_la-exprfilter.lo
src/core/exprfilter.cpp:1642:50: error: ‘numeric_limits’ is not a member of ‘std’
 1642 |     static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                  ^~~~~~~~~~~~~~
src/core/exprfilter.cpp:1642:66: error: expected primary-expression before ‘>’ token
 1642 | static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                              ^

src/core/exprfilter.cpp:1642:69: error: ‘::digits’ has not been declared
 1642 | static T clamp_int(float x, int depth = std::numeric_limits<T>::digits)
      |                                                                 ^~~~~~

src/core/exprfilter.cpp: In static member function ‘static T {anonymous}::ExprInterpreter::clamp_int(float, int)’:
src/core/exprfilter.cpp:1645:87: error: ‘numeric_limits’ is not a member of ‘std’
 1645 | <T>(std::lrint(std::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                             ^~~~~~~~~~~~~~

src/core/exprfilter.cpp:1645:103: error: expected primary-expression before ‘>’ token
 1645 | td::min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                             ^

src/core/exprfilter.cpp:1645:106: error: ‘::min’ has not been declared; did you mean ‘std::min’?
 1645 | :min(std::max(x, static_cast<float>(std::numeric_limits<T>::min())), maxval)));
      |                                                             ^~~
      |                                                             std::min
In file included from /usr/include/c++/11/algorithm:62,
                 from src/core/exprfilter.cpp:21:
/usr/include/c++/11/bits/stl_algo.h:3455:5: note: ‘std::min’ declared here
 3455 |     min(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make: *** [Makefile:1625: src/core/libexprfilter_la-exprfilter.lo] Error 1
```

**Comment by richieloro** [comment]
JUST TESTED IT  on a VM  and I still get errors, it's not a fix. I give up...
```shell
[testr@fedora vapoursynth]$ make -j4
  CYTHON   src/cython/vapoursynth.c
  CXX      src/vspipe/vspipe.o
  CXX      src/core/libvapoursynth_la-boxblurfilter.lo
  CXX      src/vsscript/libvapoursynth_script_la-vsscript.lo
/usr/lib64/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/testr/.installs/vapoursynth/src/cython/vapoursynth.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
  CXX      src/core/libvapoursynth_la-cachefilter.lo
  CXX      src/core/libvapoursynth_la-cpufeatures.lo
  CXX      src/core/libvapoursynth_la-genericfilters.lo
  CXX      src/core/kernel/libvapoursynth_la-cpulevel.lo
  CXX      src/core/kernel/libvapoursynth_la-generic.lo
  CC       src/core/kernel/libvapoursynth_la-merge.lo
  CC       src/core/kernel/libvapoursynth_la-planestats.lo
src/core/kernel/merge.c: In function ‘vs_mask_merge_premul_word_c’:
src/core/kernel/merge.c:178: warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
  178 | #pragma warning(push)
      | 
src/core/kernel/merge.c:179: warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
  179 | #pragma warning(disable:4146)
      | 
src/core/kernel/merge.c:185: warning: ignoring ‘#pragma warning ’ [-Wunknown-pragmas]
  185 | #pragma warning(pop)
      | 
  CC       src/core/kernel/libvapoursynth_la-transpose.lo
  CXX      src/core/libvapoursynth_la-lutfilters.lo
  CC       src/core/libvapoursynth_la-mergefilters.lo
  CC       src/core/libvapoursynth_la-reorderfilters.lo
  CXX      src/core/libvapoursynth_la-settings.lo
  CC       src/core/libvapoursynth_la-simplefilters.lo
  CXX      src/core/libvapoursynth_la-textfilter.lo
  CXX      src/core/libvapoursynth_la-vsapi.lo
  CXX      src/core/libvapoursynth_la-vscore.lo
  CXX      src/core/libvapoursynth_la-vslog.lo
  CXX      src/core/libvapoursynth_la-vsresize.lo
  CXX      src/core/libvapoursynth_la-vsthreadpool.lo
  CXX      src/core/kernel/x86/libvapoursynth_la-generic_sse2.lo
  CC       src/core/kernel/x86/libvapoursynth_la-merge_sse2.lo
  CC       src/core/kernel/x86/libvapoursynth_la-planestats_sse2.lo
  CC       src/core/kernel/x86/libvapoursynth_la-transpose_sse2.lo
  CXX      src/core/libexprfilter_la-exprfilter.lo
  CXX      src/core/kernel/x86/libvapoursynth_avx2_la-generic_avx2.lo
  CC       src/core/kernel/x86/libvapoursynth_avx2_la-merge_avx2.lo
  CC       src/core/kernel/x86/libvapoursynth_avx2_la-planestats_avx2.lo
  CC       src/filters/subtext/libsubtext_la-text.lo
  CC       src/filters/subtext/libsubtext_la-common.lo
  CXX      src/filters/subtext/libsubtext_la-image.lo
  CXX      src/filters/subtext/libsubtext_la-toass.lo
src/filters/subtext/image.cpp: In function ‘void imageFileCreate(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*)’:
src/filters/subtext/image.cpp:361:21: warning: ‘void av_register_all()’ is deprecated [-Wdeprecated-declarations]
  361 |     av_register_all();
      |                     ^
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:1955:6: note: declared here
 1955 | void av_register_all(void);
      |      ^~~~~~~~~~~~~~~
src/filters/subtext/image.cpp:362:26: warning: ‘void avcodec_register_all()’ is deprecated [-Wdeprecated-declarations]
  362 |     avcodec_register_all();
      |                          ^
In file included from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavcodec/avcodec.h:2767:6: note: declared here
 2767 | void avcodec_register_all(void);
      |      ^~~~~~~~~~~~~~~~~~~~
src/filters/subtext/image.cpp:430:66: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  430 |             if (!isSupportedCodecID(fctx->streams[stream_index]->codec->codec_id))
      |                                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:430:66: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  430 |             if (!isSupportedCodecID(fctx->streams[stream_index]->codec->codec_id))
      |                                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:430:66: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  430 |             if (!isSupportedCodecID(fctx->streams[stream_index]->codec->codec_id))
      |                                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:434:58: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  434 |                 if (isSupportedCodecID(fctx->streams[i]->codec->codec_id)) {
      |                                                          ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:434:58: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  434 |                 if (isSupportedCodecID(fctx->streams[i]->codec->codec_id)) {
      |                                                          ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:434:58: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  434 |                 if (isSupportedCodecID(fctx->streams[i]->codec->codec_id)) {
      |                                                          ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:448:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  448 |         AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:448:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  448 |         AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:448:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  448 |         AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:458:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  458 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:458:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  458 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:458:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  458 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:462:69: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  462 |             memcpy(d.avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:462:69: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  462 |             memcpy(d.avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:462:69: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  462 |             memcpy(d.avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:482:56: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  482 |     av_opt_get_image_size(fctx->streams[stream_index]->codec, "video_size", 0, &d.vi.width, &d.vi.height);
      |                                                        ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:482:56: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  482 |     av_opt_get_image_size(fctx->streams[stream_index]->codec, "video_size", 0, &d.vi.width, &d.vi.height);
      |                                                        ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:482:56: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  482 |     av_opt_get_image_size(fctx->streams[stream_index]->codec, "video_size", 0, &d.vi.width, &d.vi.height);
      |                                                        ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:487:27: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  487 |     av_init_packet(&packet);
      |                           ^
In file included from /usr/include/ffmpeg/libavcodec/bsf.h:30,
                 from /usr/include/ffmpeg/libavcodec/avcodec.h:44,
                 from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
src/filters/subtext/image.cpp:514:50: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  514 |                 if (fctx->streams[stream_index]->codec->codec_id == AV_CODEC_ID_DVD_SUBTITLE) {
      |                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:514:50: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  514 |                 if (fctx->streams[stream_index]->codec->codec_id == AV_CODEC_ID_DVD_SUBTITLE) {
      |                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:514:50: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  514 |                 if (fctx->streams[stream_index]->codec->codec_id == AV_CODEC_ID_DVD_SUBTITLE) {
      |                                                  ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:653:52: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  653 |             AVCodecID codec_id = fctx->streams[i]->codec->codec_id;
      |                                                    ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:653:52: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  653 |             AVCodecID codec_id = fctx->streams[i]->codec->codec_id;
      |                                                    ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:653:52: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  653 |             AVCodecID codec_id = fctx->streams[i]->codec->codec_id;
      |                                                    ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:671:53: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  671 |             av_opt_get_image_size(fctx->streams[i]->codec, "video_size", 0, &width, &height);
      |                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:671:53: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  671 |             av_opt_get_image_size(fctx->streams[i]->codec, "video_size", 0, &width, &height);
      |                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/image.cpp:671:53: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  671 |             av_opt_get_image_size(fctx->streams[i]->codec, "video_size", 0, &width, &height);
      |                                                     ^~~~~
In file included from src/filters/subtext/image.cpp:8:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp: In function ‘ASS_Track* convertToASS(const char*, const char*, size_t, ASS_Library*, const char*, const char*, char*, size_t)’:
src/filters/subtext/toass.cpp:64:21: warning: ‘void av_register_all()’ is deprecated [-Wdeprecated-declarations]
   64 |     av_register_all();
      |                     ^
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:1955:6: note: declared here
 1955 | void av_register_all(void);
      |      ^~~~~~~~~~~~~~~
src/filters/subtext/toass.cpp:65:26: warning: ‘void avcodec_register_all()’ is deprecated [-Wdeprecated-declarations]
   65 |     avcodec_register_all();
      |                          ^
In file included from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavcodec/avcodec.h:2767:6: note: declared here
 2767 | void avcodec_register_all(void);
      |      ^~~~~~~~~~~~~~~~~~~~
src/filters/subtext/toass.cpp:130:60: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  130 |     enum AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                            ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:130:60: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  130 |     enum AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                            ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:130:60: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  130 |     enum AVCodecID codec_id = fctx->streams[stream_index]->codec->codec_id;
      |                                                            ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:149:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  149 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:149:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  149 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:149:59: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  149 |         int extradata_size = fctx->streams[stream_index]->codec->extradata_size;
      |                                                           ^~~~~
In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:156:67: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  156 |       memcpy(avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                             ^~~~~

In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:156:67: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  156 |       memcpy(avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                             ^~~~~

In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:156:67: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  156 |       memcpy(avctx->extradata, fctx->streams[stream_index]->codec->extradata, extradata_size);
      |                                                             ^~~~~

In file included from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavformat/avformat.h:888:21: note: declared here
  888 |     AVCodecContext *codec;
      |                     ^~~~~
src/filters/subtext/toass.cpp:220:27: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  220 |     av_init_packet(&packet);
      |                           ^
In file included from /usr/include/ffmpeg/libavcodec/bsf.h:30,
                 from /usr/include/ffmpeg/libavcodec/avcodec.h:44,
                 from /usr/include/ffmpeg/libavformat/avformat.h:312,
                 from src/filters/subtext/toass.cpp:10:
/usr/include/ffmpeg/libavcodec/packet.h:488:6: note: declared here
  488 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
  CC       src/filters/subtext/libsubtext_la-toutf8.lo
  CC       src/filters/eedi3/libeedi3_la-eedi3.lo
  CXX      src/filters/imwri/libimwri_la-imwri.lo
  CXX      src/filters/misc/libmiscfilters_la-miscfilters.lo
src/filters/misc/miscfilters.cpp: In function ‘void averageFramesFloatSSE2(const {anonymous}::AverageFrameData*, const VSFrameRef* const*, VSFrameRef*, int, const VSAPI*)’:
src/filters/misc/miscfilters.cpp:480:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
  480 |     for (int i = 0; i < numSrcs; ++i)
      |                     ~~^~~~~~~~~
src/filters/misc/miscfilters.cpp: In function ‘void process_frame_hysteresis(const VSFrameRef*, const VSFrameRef*, VSFrameRef*, const VSFormat*, const HysteresisData*, const VSAPI*)’:
src/filters/misc/miscfilters.cpp:759:53: error: ‘numeric_limits’ is not a member of ‘std’
  759 |                         label[width * y + x] = std::numeric_limits<uint8_t>::max();
      |                                                     ^~~~~~~~~~~~~~
src/filters/misc/miscfilters.cpp:759:75: error: expected primary-expression before ‘>’ token
  759 |             label[width * y + x] = std::numeric_limits<uint8_t>::max();
      |                                                               ^

src/filters/misc/miscfilters.cpp:759:78: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  759 |             label[width * y + x] = std::numeric_limits<uint8_t>::max();
      |                                                                  ^~~
      |                                                                  std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from src/filters/misc/miscfilters.cpp:21:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
src/filters/misc/miscfilters.cpp:771:71: error: ‘numeric_limits’ is not a member of ‘std’
  771 |                               label[width * yy + xx] = std::numeric_limits<uint8_t>::max();
      |                                                             ^~~~~~~~~~~~~~

src/filters/misc/miscfilters.cpp:771:93: error: expected primary-expression before ‘>’ token
  771 |           label[width * yy + xx] = std::numeric_limits<uint8_t>::max();
      |                                                               ^

src/filters/misc/miscfilters.cpp:771:96: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  771 |           label[width * yy + xx] = std::numeric_limits<uint8_t>::max();
      |                                                                  ^~~
      |                                                                  std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from src/filters/misc/miscfilters.cpp:21:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make: *** [Makefile:1639: src/filters/misc/libmiscfilters_la-miscfilters.lo] Error 1
make: *** Waiting for unfinished jobs....
```
